name: SSLWeedMap
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - accelerate=0.29.2=pyhd8ed1ab_0
  - aiohttp=3.9.5=py311h459d7ec_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alembic=1.13.1=pyhd8ed1ab_1
  - alsa-lib=1.2.8=h166bdaf_0
  - altair=5.3.0=pyhd8ed1ab_0
  - aom=3.5.0=h27087fc_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.0=hf8751d9_2
  - aws-c-cal=0.6.0=h93469e0_0
  - aws-c-common=0.8.23=hd590300_0
  - aws-c-compression=0.2.17=h862ab75_1
  - aws-c-event-stream=0.3.1=h9599702_1
  - aws-c-http=0.7.11=hbe98c3e_0
  - aws-c-io=0.13.28=h3870b5a_0
  - aws-c-mqtt=0.8.14=h2e270ba_2
  - aws-c-s3=0.3.13=heb0bb06_2
  - aws-c-sdkutils=0.1.11=h862ab75_1
  - aws-checksums=0.1.16=h862ab75_1
  - aws-crt-cpp=0.20.3=he9c0e7f_4
  - aws-sdk-cpp=1.10.57=hbc2ea52_17
  - blas=1.0=mkl
  - blinker=1.8.1=pyhd8ed1ab_0
  - blosc=1.21.5=h0f2a231_0
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py311ha362b79_9
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - c-blosc2=2.12.0=hb4ffafa_0
  - ca-certificates=2024.6.2=hbcca054_0
  - cachetools=5.3.3=pyhd8ed1ab_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2024.6.2=pyhd8ed1ab_0
  - cfitsio=4.2.0=hd9d235c_0
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=6.8.2=py311h38be061_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py311h9547e67_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.14.7=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.1=py311hb755f60_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - easydict=1.9=py_0
  - einops=0.8.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hc118613_108
  - filelock=3.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py311h459d7ec_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.1=py311h459d7ec_0
  - fsspec=2023.10.0=pyhca7485f_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glib=2.80.0=hf2295e7_6
  - glib-tools=2.80.0=hde27a5a_6
  - glog=0.6.0=h6f12383_0
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.5=py311he48d604_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h59595ed_1003
  - greenlet=3.0.3=py311hb755f60_0
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.38=hd590300_0
  - harfbuzz=6.0.0=h8e241bc_0
  - huggingface_hub=0.17.3=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.7=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py311ha5a3c35_0
  - imagecodecs-lite=2019.12.3=py311h1f0f07a_7
  - imageio=2.34.2=pyh12aca89_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.4.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py311h9547e67_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libarrow=12.0.1=h657c46f_7_cpu
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libavif=0.11.1=h8182462_2
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.5.147=0
  - libcurl=8.1.2=h409715c_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h77fa898_6
  - libgcrypt=1.10.3=hd590300_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=13.2.0=h69a702a_6
  - libgfortran5=13.2.0=h43f5ff8_6
  - libglib=2.80.0=hf2295e7_6
  - libgomp=13.2.0=h77fa898_6
  - libgoogle-cloud=2.12.0=h840a212_1
  - libgpg-error=1.49=h4f305b6_0
  - libgrpc=1.56.2=h3905398_1
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - libllvm15=15.0.7=hadd5161_1
  - libllvm16=16.0.1=hadd5161_0
  - libnghttp2=1.58.0=h47da74e_0
  - libnl=3.9.0=hd590300_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.18=h4ab18f5_2
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.43=h2797004_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=4.23.3=hd1fb520_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_6
  - libsystemd0=253=h8c4010b_1
  - libthrift=0.18.1=h5e4af38_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_1
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=hd590300_5
  - libzopfli=1.0.3=h9c3ff4c_0
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - mako=1.3.3=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311h459d7ec_0
  - matplotlib=3.8.4=py311h38be061_0
  - matplotlib-base=3.8.4=py311h54ef318_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2022.2.1=h84fe81f_16997
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.5=py311h459d7ec_0
  - multiprocess=0.70.15=py311h459d7ec_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=3.3=pyhd8ed1ab_1
  - nspr=4.35=h27087fc_0
  - nss=3.98=h1d7d5a4_0
  - numpy=1.26.4=py311h64a7726_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.6=h4ab18f5_0
  - optuna=3.6.0=pyhd8ed1ab_0
  - orc=1.9.0=h385abfd_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py311h320fe9a_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py311h50def17_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - prompt-toolkit=3.0.42=pyha770c72_0
  - protobuf=4.23.3=py311hbec7ed6_0
  - psutil=5.9.8=py311h459d7ec_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=12.0.1=py311h39c9aba_7_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py311hf0fb5b6_5
  - pyqt5-sip=12.12.2=py311hb755f60_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.6=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py311h459d7ec_0
  - python_abi=3.11=4_cp311
  - pytorch=2.3.0=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pywavelets=1.6.0=py311h18e1886_0
  - pyyaml=6.0.1=py311h459d7ec_1
  - pyzmq=26.0.2=py311h08a0b41_0
  - qt-main=5.15.8=h5d23da1_6
  - rdma-core=51.0=hd3aeb46_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - regex=2024.4.28=py311h331c9d8_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rpds-py=0.18.0=py311h46250e7_0
  - ruamel.yaml=0.18.6=py311h459d7ec_0
  - ruamel.yaml.clib=0.2.8=py311h459d7ec_0
  - s2n=1.3.46=h06160fa_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.4.3=py311h46250e7_0
  - scikit-image=0.24.0=py311h14de704_1
  - scikit-learn=1.4.2=py311hc009520_0
  - scipy=1.13.0=py311h64a7726_0
  - sentry-sdk=2.0.1=pyhd8ed1ab_0
  - setproctitle=1.3.3=py311h459d7ec_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - sip=6.7.12=py311hb755f60_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlalchemy=2.0.29=py311h459d7ec_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - streamlit=1.33.0=pyhd8ed1ab_1
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.9.0=hf52228f_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2023.8.12=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.14.1=py311h6640629_2
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - torchaudio=2.3.0=py311_cu121
  - torchmetrics=1.3.2=pyhd8ed1ab_0
  - torchtriton=2.3.0=py311
  - torchvision=0.18.0=py311_cu121
  - tornado=6.4=py311h459d7ec_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - transformers=4.35.2=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - tzlocal=5.2=py311h38be061_0
  - ucx=1.14.1=h0aa22dc_2
  - urllib3=2.2.1=pyhd8ed1ab_0
  - validators=0.28.1=pyhd8ed1ab_0
  - wandb=0.16.5=pyhd8ed1ab_0
  - watchdog=4.0.0=py311h38be061_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py311h459d7ec_0
  - zeromq=4.3.5=h59595ed_1
  - zfp=1.0.1=hac33072_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - fastcore==1.5.48
      - lovely-numpy==0.2.12
      - lovely-tensors==0.1.15
      - opencv-python==4.9.0.80
